NAME = fragtrap

src = main.cpp ClapTrap.cpp ScavTrap.cpp FragTrap.cpp
CC = c++

obj = $(src:.cpp=.o)

flags = -Wall -Wextra -Werror -std=c++98

all: $(NAME)

$(NAME): $(obj)
	$(CC)  $(flags) $(obj) -o $(NAME)

%.o: %.cpp FragTrap.hpp ScavTrap.hpp ClapTrap.hpp
	$(CC) $(flags) -c $< -o $@

clean:
	rm -rf $(obj)

fclean: clean
	rm -rf $(NAME)

re: fclean all